### PR TITLE
Aurecon verb intergration

### PR DESCRIPTION
**Pull request by secretlyagoblin**
We've added our verb nurbs C# library wrapper in as a submodule and we're using this as the basis of many of the nurbs curve types. Might not be suitable if you don't want the codebase to be reliant on nurbs.

### CODE REVIEW

**Comment by didimitrie** [comment]
@secretlyagoblin if you're happy with this, i'm good! I think @cwmorse might be on holidays now, so merge away. 

Verbnurbs is super cool, and I don't mind a dependency on it  at all.

**Comment by cwmorse** [comment]
I would personally lean towards reducing dependencies, just to keep things as simple as possible. 

In my workflow, I'm thinking about unity+speckle as basically a viewer, in which case the display values should be enough for curves and breps for me. That being said, the potential to work with nurbs directly even on a basic level in unity (vr/hololens/etc) sounds like fun and verb sure seems like the way to go for that. I'll be interested to see how others are using Unity with speckle.

**Comment by didimitrie** [comment]
@cwmorse true that. I'm not a unity user, and am unsure of how it will be used in practice, but just noticed the #speckle-unity channel, so i'm sure there's going to be plenty of fun times ahead :D

**Comment by cwmorse** [comment]
Hmm... perhaps spoke too soon re: verb. I'm not sure how well it plays with UWP? It worked in the Unity editor, but lots of compile errors when deploying to hololens. @secretlyagoblin is this something you've looked at yet?

As a temporary compromise, I moved the nurbs related converter things into SpeckleNurbsConverter.cs, so for hololens all I need to do is delete that file and not bring in the UnityNurbs folder.

Not sure what the ideal long term solution is

**Pull request merged**
